CREATE TABLE periods (
  id                   CHAR(7)      NOT NULL,
  title                VARCHAR(120) NOT NULL,
  currency             VARCHAR(8)   NOT NULL DEFAULT 'IRT',
  owner_id             VARCHAR(32)  NOT NULL,
  created_at           DATETIME(3)  NOT NULL,
  updated_at           DATETIME(3)  NOT NULL,
  version              INT          NOT NULL DEFAULT 0,
  kind                 ENUM('split','banker','pot') NOT NULL DEFAULT 'split',
  banker_member_id     VARCHAR(32)  NULL,
  template             VARCHAR(32)  NOT NULL DEFAULT 'custom',
  round_to             SMALLINT     NOT NULL DEFAULT 0,
  building_charge      BIGINT       NULL,
  lunch_turn_member_id VARCHAR(32)  NULL,
  encrypted            TINYINT(1)   NOT NULL DEFAULT 0,
  visibility           ENUM('private','public') NOT NULL DEFAULT 'private',
  PRIMARY KEY (id),
  KEY ix_periods_owner (owner_id),
  KEY ix_periods_banker (banker_member_id),
  KEY ix_periods_lunch (lunch_turn_member_id),
  CONSTRAINT fk_periods_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE members (
  id               VARCHAR(32)   NOT NULL,
  period_id        CHAR(7)       NOT NULL,
  user_id          VARCHAR(32)   NULL,
  guest_key        VARCHAR(64)   NULL,
  display_name     VARCHAR(80)   NOT NULL,
  weight_default   DECIMAL(12,4) NOT NULL DEFAULT 1,
  role             ENUM('owner','member','viewer') NOT NULL DEFAULT 'member',
  phone            VARCHAR(15)   NULL,
  email            VARCHAR(191)  NULL,
  card_number      VARCHAR(16)   NULL,
  sheba            VARCHAR(32)   NULL,
  card_holder_name VARCHAR(80)   NULL,
  bank_name        VARCHAR(80)   NULL,
  exclude_from_new TINYINT(1)    NOT NULL DEFAULT 0,
  is_pot           TINYINT(1)    NOT NULL DEFAULT 0,
  unit_label       VARCHAR(40)   NULL,
  pot_period       CHAR(7) AS (IF(is_pot = 1, period_id, NULL)) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uq_member_user (period_id, user_id),
  UNIQUE KEY uq_member_guest (period_id, guest_key),
  UNIQUE KEY uq_member_one_pot (pot_period),
  KEY ix_members_period (period_id),
  KEY ix_members_user (user_id),
  CONSTRAINT fk_members_period FOREIGN KEY (period_id) REFERENCES periods(id) ON DELETE CASCADE,
  CONSTRAINT fk_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
